apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-pv"
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- if .Values.storage.labels }}
  {{- .Values.storage.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.storage.annotations }}
  annotations:
  {{- .Values.storage.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  local:
    path: /tmp
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  {{- .Values.storage.accessModes | toYaml | nindent 4 }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mycroft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- if .Values.storage.labels }}
  {{- .Values.storage.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.storage.annotations }}
  annotations:
  {{- .Values.storage.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  accessModes:
  {{- .Values.storage.accessModes | toYaml | nindent 4 }}