{{- $cfg := required "configuration.servers.databases.config.password is required" .Values.configuration.servers.databases.config.password -}}
{{- $log := required "configuration.servers.databases.log.password is required" .Values.configuration.servers.databases.log.password -}}
{{- $web := required "configuration.servers.databases.web.password is required" .Values.configuration.servers.databases.web.password -}}
{{- $installer := required "configuration.installerPassword is required" .Values.configuration.installerPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluxcp.fullname" . }}
  labels:
    {{- include "fluxcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLUXCP_DB_CONFIG_PASSWORD: {{ $cfg | quote }}
  FLUXCP_DB_LOG_PASSWORD: {{ $log | quote }}
  FLUXCP_DB_WEB_PASSWORD: {{ $web | quote }}
  FLUXCP_INSTALLER_PASSWORD: {{ $installer | quote }}
