---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "romm.fullname" . }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "romm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "romm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if not .Values.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "romm.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: romm
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.containerPort }}
              protocol: TCP
          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.server.env.TZ }}
            - name: TZ
              value: {{ . | quote }}
            {{- end }}
            {{- if not (kindIs "invalid" .Values.server.env.PUID) }}
            - name: PUID
              value: {{ .Values.server.env.PUID | quote }}
            {{- end }}
            {{- if not (kindIs "invalid" .Values.server.env.PGID) }}
            - name: PGID
              value: {{ .Values.server.env.PGID | quote }}
            {{- end }}
            - name: ROMM_DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: romm_db_driver
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: db_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: db_user
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: db_password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.redis.existingSecret }}{{ .Values.redis.existingSecret }}{{ else }}{{ include "romm.secretName" . }}{{ end }}
                  key: {{ if .Values.redis.existingSecret }}redis-password{{ else }}redis_password{{ end }}
            - name: IGDB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: igdb_client_id
            - name: IGDB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: igdb_client_secret
            - name: MOBYGAMES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: moby_api_key
            - name: ROMM_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: secret_key
            - name: ROMM_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: initial_username
            - name: ROMM_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "romm.secretName" . }}
                  key: initial_password
            {{- with .Values.server.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /romm/config
            - name: assets
              mountPath: /romm/assets
            - name: resources
              mountPath: /romm/resources
            - name: library
              mountPath: /romm/library
              {{- if .Values.storage.library.readOnly }}
              readOnly: true
              {{- end }}
            {{- with .Values.server.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "romm.fullname" . }}-config
        - name: resources
          {{- if .Values.storage.resources.persist }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" . }}-resources
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: assets
          {{- if .Values.storage.assets.persist }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" . }}-assets
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: library
          {{- if and .Values.storage.library.persist .Values.storage.library.hostPath }}
          hostPath:
            path: {{ .Values.storage.library.hostPath | quote }}
          {{- else if .Values.storage.library.persist }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" . }}-library
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.server.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
