{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "romm.fullname" . }}-secrets
  labels:
    {{- include "romm.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.server.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  romm_db_driver: {{ .Values.server.configuration.database.driver | default "mariadb" | b64enc | quote }}
  db_host: {{ required "server.configuration.database.host is required (or set existingSecret)" .Values.server.configuration.database.host | b64enc | quote }}
  db_port: {{ .Values.server.configuration.database.port | toString | b64enc | quote }}
  db_name: {{ .Values.server.configuration.database.name | b64enc | quote }}
  db_user: {{ .Values.server.configuration.database.username | b64enc | quote }}
  db_password: {{ required "server.configuration.database.password is required (or set existingSecret)" .Values.server.configuration.database.password | b64enc | quote }}
  {{- if not .Values.redis.existingSecret }}
  redis_host: {{ .Values.redis.host | b64enc | quote }}
  redis_port: {{ .Values.redis.port | toString | b64enc | quote }}
  redis_password: {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  redis_host: {{ .Values.redis.host | b64enc | quote }}
  redis_port: {{ .Values.redis.port | toString | b64enc | quote }}
  {{- end }}
  igdb_client_id: {{ .Values.server.configuration.igdbClientId | b64enc | quote }}
  igdb_client_secret: {{ .Values.server.configuration.igdbClientSecret | b64enc | quote }}
  moby_api_key: {{ .Values.server.configuration.mobyApiKey | b64enc | quote }}
  secret_key: {{ .Values.server.configuration.secretKey | default (randAlphaNum 64) | b64enc | quote }}
  initial_username: {{ .Values.server.configuration.initialUsername | b64enc | quote }}
  initial_password: {{ .Values.server.configuration.initialPassword | default (include "romm.initial_user.password" .) | b64enc | quote }}
{{- end -}}
