{{- define "romm.initial_user.password" -}}
{{- randAlphaNum 32 | nospace -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  {{- with .Values.server.annotations }}
  annotations:
  {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}-secrets"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-secrets"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.server.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  db_host: {{ .Values.server.configuration.database.host | b64enc }}
  db_name: {{ .Values.server.configuration.database.name | b64enc }}
  db_user: {{ .Values.server.configuration.database.username | b64enc }}
  db_password: {{ .Values.server.configuration.database.password | b64enc }}
  igdb_client_id: {{ .Values.server.configuration.igdbClientId | b64enc }}
  igdb_client_secret: {{ .Values.server.configuration.igdbClientSecret | b64enc }}
  moby_api_key: {{ .Values.server.configuration.mobyApiKey | b64enc }}
  secret_key: {{ .Values.server.configuration.secretKey | b64enc }}
  initial_username: {{ .Values.server.configuration.initialUsername | b64enc }}
  initial_password: {{- if .Values.server.configuration.initialPassword }} "{{ .Values.server.configuration.initialPassword | b64enc }}" {{ else }} "{{ include "romm.initial_user.password" .  | b64enc}}" {{ end }}