---
{{ if .Values.server.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  {{- with .Values.server.service.annotations }}
  annotations:
  {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-svc"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.server.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/component: "{{ .Release.Name }}-server"
  ports:
    - name: webserver
      port: {{ .Values.server.service.port }}
      protocol: TCP
      targetPort: 8080
  type: {{ .Values.server.service.type }}
{{ end }}