{{- $cPwd := randAlphaNum 12 | nospace -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld.serverFullname" . }}-env
  {{- with .Values.server.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "palworld.serverLabels" . | nindent 4 }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  PUID: {{ .Values.server.config.puid | quote }}
  PGID: {{ .Values.server.config.pgid | quote }}
  PORT: {{ .Values.server.config.port | quote }}
  PLAYERS: {{ .Values.server.config.max_players | quote }}
  MULTITHREADING: {{ .Values.server.config.multithreading | quote }}
  {{- if .Values.server.config.rcon.enable }}
  RCON_ENABLED: "true"
  RCON_PORT: {{ .Values.server.config.rcon.port | quote }}
  {{- end }}
  {{- if .Values.server.config.community.enable }}
  COMMUNITY: "true"
  SERVER_PASSWORD: {{- if .Values.server.config.community.password }} {{ .Values.server.config.community.password | quote }} {{- else }} {{ $cPwd | quote }} {{- end }}
  {{- end }}
  {{- if .Values.server.config.server_name }}
  SERVER_NAME: {{ regexReplaceAll "\\W+" .Values.server.config.server_name "_" | quote }}
  {{- else }}
  SERVER_NAME: {{ printf "%s_%s" "palworld" (randAlphaNum 6 | nospace) | quote }}
  {{- end }}
  TZ: {{ .Values.server.config.timezone | quote }}
  PUBLIC_IP: {{ .Values.server.config.public_ip | quote }}
  PUBLIC_PORT: {{ .Values.server.config.public_port | quote }}
  SERVER_DESCRIPTION: {{ .Values.server.config.server_description | quote }}
  UPDATE_ON_BOOT: {{ .Values.server.config.update_on_boot | quote }}
  QUERY_PORT: {{ .Values.server.config.query_port | quote }}
  {{- with .Values.server.config.world_parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld.apiFullname" . }}-env
  {{- with .Values.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "palworld.apiLabels" . | nindent 4 }}
    {{- with .Values.api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  PALWORLD_SERVER_IP_ADDRESS: {{ default (include "palworld.serverFullname" .) .Values.api.config.server_host | quote }}
  PALWORLD_RCON_PORT: {{ .Values.api.config.rcon_port | quote }}
  INFO_CACHE_DURATION_MS: {{ .Values.api.config.info_cache_duration | quote }}
  PORT: {{ .Values.api.config.port | quote }}
{{- end }}
