{{- include "palworld.validateApi" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.serverFullname" . }}
  labels:
    {{- include "palworld.serverLabels" . | nindent 4 }}
    {{- with .Values.server.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.server.strategy }}
  selector:
    matchLabels:
      {{- include "palworld.serverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.server.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "palworld.serverLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.server.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "palworld.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.server.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml (default .Values.podSecurityContext .Values.server.podSecurityContext) | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.api.attach_to_game_server }}
        - name: api
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.imagePullPolicy }}
          securityContext:
            {{- toYaml (default .Values.securityContext .Values.api.securityContext) | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "palworld.apiFullname" . }}-env
          env:
            - name: PALWORLD_RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "palworld.serverFullname" . }}
                  key: rconPassword
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "palworld.serverFullname" . }}
                  key: bearerToken
          ports:
            - name: api
              containerPort: {{ .Values.api.config.port }}
              protocol: TCP
          {{- with .Values.api.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: server
          image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.imagePullPolicy }}
          securityContext:
            {{- toYaml (default .Values.securityContext .Values.server.securityContext) | nindent 12 }}
          ports:
            {{- with .Values.server.ports }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "palworld.serverFullname" . }}
                  key: rconPassword
          envFrom:
            - configMapRef:
                name: {{ include "palworld.serverFullname" . }}-env
          {{- with .Values.server.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: datadir
              mountPath: /palworld
      volumes:
        - name: datadir
          persistentVolumeClaim:
            {{- if .Values.server.storage.external }}
            claimName: {{ .Values.server.storage.externalName | quote }}
            {{- else }}
            claimName: {{ include "palworld.serverFullname" . }}-datadir
            {{- end }}
{{- if .Values.api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.apiFullname" . }}
  labels:
    {{- include "palworld.apiLabels" . | nindent 4 }}
    {{- with .Values.api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.api.strategy }}
  selector:
    matchLabels:
      {{- include "palworld.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "palworld.apiLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "palworld.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      securityContext:
        {{- toYaml (default .Values.podSecurityContext .Values.api.podSecurityContext) | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.imagePullPolicy }}
          securityContext:
            {{- toYaml (default .Values.securityContext .Values.api.securityContext) | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "palworld.apiFullname" . }}-env
          env:
            - name: PALWORLD_RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "palworld.serverFullname" . }}
                  key: rconPassword
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "palworld.serverFullname" . }}
                  key: bearerToken
          ports:
            - name: api
              containerPort: {{ .Values.api.config.port }}
              protocol: TCP
          {{- with .Values.api.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
