{{- if not .Values.server.storage.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "palworld.serverFullname" . }}-datadir
  {{- $annotations := .Values.server.config.annotations | default dict }}
  {{- if .Values.server.storage.preventDelete }}
  {{- $annotations = merge (dict "helm.sh/resource-policy" "keep") $annotations }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "palworld.serverLabels" . | nindent 4 }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.storage.size | quote }}
  {{- with .Values.server.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
