{{- include "palworld.validateApi" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "palworld.serverFullname" . }}
  {{- with .Values.server.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "palworld.serverLabels" . | nindent 4 }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  rconPassword: {{ include "palworld.rconPassword" . | quote }}
  {{- if .Values.api.enabled }}
  bearerToken: {{ include "palworld.bearerToken" . | quote }}
  {{- end }}
