{{- if .Values.server.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.serverFullname" . }}
  labels:
    {{- include "palworld.serverLabels" . | nindent 4 }}
    {{- with .Values.server.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "palworld.serverSelectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.api.attach_to_game_server }}
    - name: api
      port: {{ .Values.api.service.port }}
      protocol: {{ .Values.api.service.protocol }}
      targetPort: {{ .Values.api.config.port }}
    {{- end }}
    {{- with .Values.server.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- if and .Values.api.enabled .Values.api.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.apiFullname" . }}
  labels:
    {{- include "palworld.apiLabels" . | nindent 4 }}
    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "palworld.apiSelectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      protocol: {{ .Values.api.service.protocol }}
      targetPort: api
{{- end }}
