{{- if .Values.gotenberg.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bigcapital.fullname" . }}-gotenberg
  labels:
    {{- include "bigcapital.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotenberg
    {{- with .Values.gotenberg.storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gotenberg.storage.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.gotenberg.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.gotenberg.storage.size }}
  volumeName: {{ include "bigcapital.fullname" . }}-gotenberg-pv
  {{- if .Values.gotenberg.storage.storageClass }}
  storageClassName: {{ .Values.gotenberg.storage.storageClass | quote }}
  {{- else }}
  storageClassName: manual
  {{- end }}
---
{{- end }}

{{- if and .Values.database.enabled .Values.database.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bigcapital.fullname" . }}-database
  labels:
    {{- include "bigcapital.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    {{- with .Values.database.storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.database.storage.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.database.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
  volumeName: {{ include "bigcapital.fullname" . }}-database-pv
  {{- if .Values.database.storage.storageClass }}
  storageClassName: {{ .Values.database.storage.storageClass | quote }}
  {{- else }}
  storageClassName: manual
  {{- end }}
---
{{- end }}

{{- if and .Values.redis.enabled .Values.redis.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bigcapital.fullname" . }}-redis
  labels:
    {{- include "bigcapital.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
    {{- with .Values.redis.storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.redis.storage.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.redis.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
  volumeName: {{ include "bigcapital.fullname" . }}-redis-pv
  {{- if .Values.redis.storage.storageClass }}
  storageClassName: {{ .Values.redis.storage.storageClass | quote }}
  {{- else }}
  storageClassName: manual
  {{- end }}
{{- end }}