---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voting-app.fullname" . }}-database-conf
  labels:
    {{- include "voting-app.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
    {{- with .Values.database.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.database.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  POSTGRES_DB: {{ .Values.database.databaseName | quote }}
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_USERNAME: {{ .Values.database.username | quote }}
  POSTGRES_HOST: {{ include "postgres.host" . | quote }}
  REDIS_HOST: {{ include "redis.host" . | quote }}
