---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "voting-app.fullname" . }}-database-conf
  namespace: {{ template "voting-app.namespace" . }}
  labels:
    app.kubernetes.io/component: "{{ template "voting-app.fullname" . }}-database-conf"
    {{- include "voting-app.labels" . | nindent 4 }}
    {{- with .Values.database.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.database.annotations }}
  annotations:
  {{- toYaml . | nindent 6 }}
  {{- end }}
data:
  POSTGRES_DB: "{{ .Values.database.databaseName }}"
  POSTGRES_USER: "{{ .Values.database.username }}"
  POSTGRES_USERNAME: "{{ .Values.database.username }}"
  POSTGRES_HOST: "{{- template "postgres.host" . -}}"
  REDIS_HOST: "{{- template "redis.host" . -}}"