---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voting-app.fullname" . }}-database-pvc
  labels:
    {{- include "voting-app.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
    {{- with .Values.database.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.database.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
  {{- with .Values.database.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
