---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-vote-svc
  labels:
    {{- include "voting-app.componentLabels" (dict "context" . "component" "vote") | nindent 4 }}
    {{- with .Values.vote.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vote.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - name: http
      port: {{ .Values.vote.service.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
  selector:
    {{- include "voting-app.componentSelectorLabels" (dict "context" . "component" "vote") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-result-svc
  labels:
    {{- include "voting-app.componentLabels" (dict "context" . "component" "result") | nindent 4 }}
    {{- with .Values.result.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.result.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - name: http
      port: {{ .Values.result.service.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
  selector:
    {{- include "voting-app.componentSelectorLabels" (dict "context" . "component" "result") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-database-svc
  labels:
    {{- include "voting-app.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
    {{- with .Values.database.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.database.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      appProtocol: postgresql
  selector:
    {{- include "voting-app.componentSelectorLabels" (dict "context" . "component" "database") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-redis-svc
  labels:
    {{- include "voting-app.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.redis.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      appProtocol: redis
  selector:
    {{- include "voting-app.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 4 }}
