namespace: rathena
image:
  imagePullPolicy: Always
  imagePullSecrets:
  - name: registry-auth
  name: ghcr.io/filipe-souza/rathena
  tag: v0.0.1-alpine
replicaCount: 1
databases:
  main:
    # -- Main database host address
    host: "127.0.0.1"
    # -- Main database host port
    port: "3306"
    # -- Main database username
    username: "ragnarok"
    # -- Main database password
    password: "ragnarok"
    # -- Main database schema name
    name: "ragnarok"
  log:
    # -- Log database host address
    host: "127.0.0.1"
    # -- Log database host port
    port: "3306"
    # -- Log database username
    username: "ragnarok"
    # -- Log database password
    password: "ragnarok"
    # -- Log database schema name
    name: "log"
servers:
  annotations: {}
  labels: {}
  # -- Sets the server_name into the char_conf.txt
  globalName: rAthena
  charServer:
    # -- Number of replicas of this pod
    replicas: 1
    livenessProbe:
      # -- Delay to start probing the pod
      initialDelaySeconds: 30
      # -- Delay between probes on the pod
      periodSeconds: 60
    service:
      # -- Enable/disables the creation of the service
      create: true
      # -- Port that service will be listening
      port: 6121
      # -- Type of service.
      type: ClusterIP
  loginServer:
    # -- Set this value to yes if going to use MySQL 8.0
    md5Password: no
    # -- Number of replicas of this pod
    replicas: 1
    livenessProbe:
      # -- Delay to start probing the pod
      initialDelaySeconds: 15
      # -- Delay between probes on the pod
      periodSeconds: 60
    service:
      # -- Enable/disables the creation of the service
      create: true
      # -- Port that service will be listening
      port: 6900
      # -- Type of service.
      type: ClusterIP
  mapServer:
    # -- Number of replicas of this pod
    replicas: 1
    livenessProbe:
      # -- Delay to start probing the pod
      initialDelaySeconds: 30
      # -- Delay between probes on the pod
      periodSeconds: 60
    service:
      # -- Enable/disables the creation of the service
      create: true
      # -- Port that service will be listening
      port: 5121
      # -- Type of service.
      type: ClusterIP
  proxyServer:
    enable: true
    image:
      name: ghcr.io/filipe-souza/rathena
      tag: wsproxy
      imagePullPolicy: Always
    # -- Number of replicas of this pod
    replicas: 1
    livenessProbe:
      # -- Delay to start probing the pod
      initialDelaySeconds: 30
      # -- Delay between probes on the pod
      periodSeconds: 60
    service:
      # -- Enable/disables the creation of the service
      create: true
      # -- Port that service will be listening
      port: 5999
      # -- Type of service.
      type: ClusterIP
  # -- Configures the credentials to be stored into the config files for the inter-server authentication.
  interServer:
    auth:
      passwd: p1
      userid: s1
  webServer:
    enable: false
    # -- Number of replicas of this pod
    replicas: 1
    livenessProbe:
      # -- Delay to start probing the pod
      initialDelaySeconds: 30
      # -- Delay between probes on the pod
      periodSeconds: 60
    service:
      # -- Enable/disables the creation of the service
      create: true
      # -- Port that service will be listening
      port: 8888
      # -- Type of service.
      type: ClusterIP