{{- $fullName := include "rathena.fullname" . -}}
{{- if .Values.servers.loginServer.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-login-server-svc
  labels:
    {{- include "rathena.componentLabels" (dict "context" . "component" "login-server") | nindent 4 }}
    {{- with .Values.servers.loginServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.servers.loginServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.servers.loginServer.service.type }}
  selector:
    {{- include "rathena.componentSelectorLabels" (dict "context" . "component" "login-server") | nindent 4 }}
  ports:
    - name: login-server
      port: {{ .Values.servers.loginServer.service.port }}
      protocol: TCP
      targetPort: login-server
{{- end }}
{{- if .Values.servers.charServer.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-char-server-svc
  labels:
    {{- include "rathena.componentLabels" (dict "context" . "component" "char-server") | nindent 4 }}
    {{- with .Values.servers.charServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.servers.charServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.servers.charServer.service.type }}
  selector:
    {{- include "rathena.componentSelectorLabels" (dict "context" . "component" "char-server") | nindent 4 }}
  ports:
    - name: char-server
      port: {{ .Values.servers.charServer.service.port }}
      protocol: TCP
      targetPort: char-server
{{- end }}
{{- if .Values.servers.mapServer.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-map-server-svc
  labels:
    {{- include "rathena.componentLabels" (dict "context" . "component" "map-server") | nindent 4 }}
    {{- with .Values.servers.mapServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.servers.mapServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.servers.mapServer.service.type }}
  selector:
    {{- include "rathena.componentSelectorLabels" (dict "context" . "component" "map-server") | nindent 4 }}
  ports:
    - name: map-server
      port: {{ .Values.servers.mapServer.service.port }}
      protocol: TCP
      targetPort: map-server
{{- end }}
{{- if and .Values.servers.webServer.enable .Values.servers.webServer.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-web-server-svc
  labels:
    {{- include "rathena.componentLabels" (dict "context" . "component" "web-server") | nindent 4 }}
    {{- with .Values.servers.webServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.servers.webServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.servers.webServer.service.type }}
  selector:
    {{- include "rathena.componentSelectorLabels" (dict "context" . "component" "web-server") | nindent 4 }}
  ports:
    - name: web-server
      port: {{ .Values.servers.webServer.service.port }}
      protocol: TCP
      targetPort: web-server
{{- end }}
{{- if and .Values.servers.proxyServer.enable .Values.servers.proxyServer.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-wsproxy-svc
  labels:
    {{- include "rathena.componentLabels" (dict "context" . "component" "wsproxy") | nindent 4 }}
    {{- with .Values.servers.proxyServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.servers.proxyServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.servers.proxyServer.service.type }}
  selector:
    {{- include "rathena.componentSelectorLabels" (dict "context" . "component" "wsproxy") | nindent 4 }}
  ports:
    - name: wsproxy
      port: {{ .Values.servers.proxyServer.service.port }}
      protocol: TCP
      targetPort: wsproxy
{{- end }}
